version: "3"
services:
  sonar:
    image: sonarqube:latest
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "80:9000"
    volumes:
      - sonar_data:/opt/SonarQube/data
      - sonar_extensions:/opt/SonarQube/extensions
      - sonar_logs:/opt/SonarQube/logs
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonartest
      SONAR_JDBC_USERNAME: sonartest
      SONAR_JDBC_PASSWORD: sonartest

  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sonartest
      POSTGRES_PASSWORD: sonartest

volumes:
  sonar_data:
  sonar_extensions:
  sonar_logs:
  postgresql:
  postgresql_data: